
java_binary(
	name = "ass_tool",
	srcs = ["AggregationSessionTool.java"],
	main_class = "org.jetbrains.ifed.engine.tff.AggregationSessionTool",
	deps = [
		"//ifed/java/src/main/org/jetbrains/ifed/engine/tff:aggregation",
	],
)

