package(default_visibility = ["//tensorflow_federated_research"])

licenses(["notice"])

py_library(
    name = "dp_utils",
    srcs = ["dp_utils.py"],
    srcs_version = "PY3",
    deps = [
        "//tensorflow_federated",
    ],
)
