package(default_visibility = ["//visibility:private"])

package_group(
    name = "impl_packages",
    packages = [
        "//tensorflow_federated/cc/core/impl/...",
        "//tensorflow_federated/python/core/impl/...",
    ],
)

package_group(name = "impl_visibility")

licenses(["notice"])
