load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//tensorflow_federated/python/analytics:__subpackages__"])

licenses(["notice"])

py_library(
    name = "analytics",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    visibility = ["//tensorflow_federated:__pkg__"],
)
