java_test(
    name = "AggregationSessionTest",
    srcs = ["AggregationSessionTest.java"],
    deps = [
        "//ifed/engine/java/src/main/com/google/tff/aggregation:aggregation",
        "@maven//:junit_junit",
    ],
    test_class = "org.jetbrains.ifed.engine.tff.AggregationSessionTest",
)
