package(default_visibility = ["//tensorflow_federated:__subpackages__"])

licenses(["notice"])

py_library(
    name = "backends",
    srcs = ["__init__.py"],
    deps = ["//tensorflow_federated/python/core/backends/mapreduce"],
)
