package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

# This exists for the API doc generator. The doc generator tool looks for API
# usage in tutorial content and links to the tutorials in the API doc content.
filegroup(
    name = "tutorials",
    srcs = glob(["**"]),
)
