package(default_visibility = ["//visibility:private"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "encoding_stage",
    srcs = ["encoding_stage.py"],
    deps = ["@six_archive//:six"],
)
