# Copyright 2022, The TensorFlow Federated Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tff-workers-deployment-1
  labels:
    app: tff-workers-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tff-workers-1
  template:
    metadata:
      labels:
        app: tff-workers-1
    spec:
      containers:
      - name: tff-workers-1
        image: gcr.io/tensorflow-federated/worker-service-test:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: tff-workers-storage-1
          mountPath: /root/worker/data
      volumes:
      - name: tff-workers-storage-1
        persistentVolumeClaim:
          claimName: tff-workers-pv-claim-1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tff-workers-deployment-2
  labels:
    app: tff-workers-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tff-workers-2
  template:
    metadata:
      labels:
        app: tff-workers-2
    spec:
      containers:
      - name: tff-workers-2
        image: gcr.io/tensorflow-federated/worker-service-test:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: tff-workers-storage-2
          mountPath: /root/worker/data
      volumes:
      - name: tff-workers-storage-2
        persistentVolumeClaim:
          claimName: tff-workers-pv-claim-2
---
kind: Service
apiVersion: v1
metadata:
  name: tff-workers-service-1
spec:
  type: LoadBalancer
  selector:
    app: tff-workers-1
  ports:
  - port: 80
    targetPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: tff-workers-service-2
spec:
  type: LoadBalancer
  selector:
    app: tff-workers-2
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tff-workers-storage-class
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tff-workers-pv-claim-1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: tff-workers-storage-class
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tff-workers-pv-claim-2
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: tff-workers-storage-class
  resources:
    requests:
      storage: 10Gi
