package(default_visibility = [
    "//tensorflow_federated/python/core/api:__pkg__",
    "//tensorflow_federated/python/core/framework:__pkg__",
    "//tensorflow_federated/python/core/impl:__pkg__",
])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "compiler",
    srcs = ["__init__.py"],
    visibility = ["//tensorflow_federated/tools:__subpackages__"],
)
