load("@rules_python//python:defs.bzl", "py_library")

package(
    default_applicable_licenses = ["//:package_license"],
    default_visibility = ["//visibility:private"],
)

licenses(["notice"])

py_library(
    name = "proto",
    srcs = ["__init__.py"],
    visibility = ["//tools/python_package:python_package_tool"],
)
