package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_library(
    name = "python",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    visibility = ["//tensorflow_federated/tools:__subpackages__"],
)
