package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_test(
    name = "sanity_test",
    srcs = ["sanity_test.py"],
    deps = ["//tensorflow_federated/proto/v0:tensorflow_federated_v0_py_pb2"],
)
