package(default_visibility = ["//visibility:private"])

licenses(["notice"])

py_binary(
    name = "test",
    srcs = ["test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = ["//tensorflow_federated"],
)
