
java_binary(
	name = "ass_tool",
	srcs = ["AggregationSessionTool.java"],
	main_class = "org.jetbrains.tff.engine.AggregationSessionTool",
	deps = [
		"//engine/java/src/main/org/jetbrains/tff/engine:aggregation",
	],
)

