package(default_visibility = ["//tensorflow_federated/python/core:__subpackages__"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "framework",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//tensorflow_federated/python/core/impl:computation_building_blocks",
        "//tensorflow_federated/python/core/impl:computation_constructing_utils",
        "//tensorflow_federated/python/core/impl:computation_wrapper_instances",
        "//tensorflow_federated/python/core/impl:intrinsic_defs",
        "//tensorflow_federated/python/core/impl:transformation_utils",
        "//tensorflow_federated/python/core/impl:transformations",
        "//tensorflow_federated/python/core/impl:type_utils",
    ],
)
