package(default_visibility = ["//tensorflow_federated:__subpackages__"])

licenses(["notice"])

py_binary(
    name = "remote_executor_example",
    srcs = ["remote_executor_example.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = ["//tensorflow_federated"],
)
