package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "examples",
    srcs = ["__init__.py"],
    deps = [
        "//tensorflow_federated/python/examples/mnist",
    ],
)
