package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0 License

# This exists for the API doc generator. It needs to exist here because the
# api_docs directory gets blown away by the tool each time it runs.
filegroup(
    name = "api_docs",
    srcs = glob(["api_docs/**"]),
)
