package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0 License

filegroup(
    name = "api_docs",
    srcs = glob(["api_docs/**"]),
)

filegroup(
    name = "tutorials",
    srcs = glob(["tutorials/**"]),
)
