package(default_visibility = ["//tensorflow_federated:__subpackages__"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "models",
    srcs = ["__init__.py"],
    deps = [":mnist"],
)

py_library(
    name = "mnist",
    srcs = ["mnist.py"],
)
