package(default_visibility = ["//tensorflow_federated:__subpackages__"])

licenses(["notice"])

py_library(
    name = "models",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [":mnist"],
)

py_library(
    name = "mnist",
    srcs = ["mnist.py"],
    srcs_version = "PY2AND3",
)
