name: Test python package

on: [push, workflow_dispatch]  # yamllint disable-line rule:truthy

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-python-package-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        create_credentials_file: true

    - name: Set up bazel repository cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE') }}
        restore-keys: ${{ runner.os }}-bazel-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Set up Python environment
      run: |
        pip install --upgrade pip
        pip --version
        pip install --upgrade numpy~=1.25
        pip freeze

    - name: Test Python package
      run: |
        bazelisk run //tensorflow_federated/tools/python_package:build_python_package \
            --build_tag_filters="-nokokoro,-nopresubmit,-requires-gpu-nvidia" \
            --google_credentials=${{ steps.auth.outputs.credentials_file_path }} \
            --remote_cache="https://storage.googleapis.com/tensorflow-federated-bazel-cache/${{ github.job }}"
